= Fingerprint Toolbox Inventory
:showtitle:
:revdate: 2020-10-21

This document contains the inventory of tools and materials that are used in the context of the toolbox.

== Overview
This document specifies requirements for tools and materials that are used to create fingerprint friction ridge artefacts.  The requirements for each tool are specified in the following tables.

The evaluator may use any tools and materials to create fingerprint artefacts as long as they meet requirements specified below. The evaluator may use any available services (e.g. rental service) to prepare any tools in a cost effective way so long as the privacy of the biometric donor is protected.

The evaluator may need to use other tools that are not specified here.

Some examples:

* A mold release / wetting agent may be applied to the finger of the test subject.  This release / agent shall be compatible with the mold material as specified by the manufacturer of the mold material.
* The evaluator may procure a vacuum chamber to aid in the degassing of cast materials if desired.
* The evaluator may apply conductive coatings to a silicone cast to make the PAI conductive.  The coatings may be carbon or metal loaded paints or inks.  The coatings may contain conductive particles or nanoparticles.  Application of the coatings may be by brush or spray.  In all cases, the evaluator shall ensure that the dried conductive coating does not fill the friction ridge valleys thereby obscuring the fingerprint pattern.

Certain commercial equipment, instruments, or materials are identified in this toolbox inventory as representative examples that may be utilized. Such identification is not intended to imply recommendation or endorsement by the BIO-iTC, nor is it intended to imply that the materials or equipment identified are necessarily the best available for the purpose. Examples may not be provided for every category. All trademarks, service marks and company names are the property of their respective owners.

== Tools Inventory
.Tool Requirements
[cols=".^1,.^1,.^3,.^2",options="header"]
|===
|ID
|Category
|Requirement
|Commercial Examples


|T.1
|Commercial fingerprint scanner
a|Commercial fingerprint scanner

* Scanner shall provide grayscale images in standard image file formats
* 1000 dpi minimum image resolution
* Rolled images preferred
* Touch/slap images acceptable
a|

|T.2
|Image processing software
a|Photograph processing software

* Can be commercial, open source or bespoke
* Can be image manipulation software that allows pixel level image processing
* Can be automatic binarization software
a|* Adobe Photoshop

* GIMP - GNU Image Manipulation Program

|T.3
|Laser printer             
a|Small Office/Home Office Laser printer

* New printer shall be purchasable at the date of testing.
a|

|T.4
|Printed Circuit Board (PCB) manufacturing kit            
a|PCB kit

* Hobbyist level commercial kit with fresh chemicals at the date of testing
a|

|T.5
|Water filter           
a|Consumer grade tap water filter

* Can be faucet or pitcher based filter
* Must meet NSF/ANSI 42 and 53 contaminant reduction standards
a|

|T.6
|Microwave oven            
a|Microwave oven

* Oven may be consumer grade
* Oven shall have a rotating turntable
a|

|===


== Materials Inventory
All materials with expiration dates shall have an expiration date of three months beyond the date of testing.

=== Cast Materials

.Cast Material Requirements
[cols=".^1,.^1,.^3,.^2",options="header"]
|===

|ID
|Category
|Requirement
|Commercial Examples

|C.1
|Non-Newtonian fluid, also known as Dilatant compound
a|Commercial or custom made compound with a chemical composition approximating:

* 65% dimethylsiloxane (hydroxy-terminated polymers with boric acid)
* 17% silica (crystalline quartz)
* 9% Hydrogenated castor oil based thixotropic agent
* 4% polydimethylsiloxane
* 1% decamethyl cyclopentasiloxane
* 1% glycerin
* 1% titanium dioxide  
a|* DOWSIL 3179 Dilatant Compound
* Molykote 3179 Dilatant Compound

|C.2
|Modeling compound              
a|Commercial or custom made compound with a composition approximating:

* 39% General purpose baking flour
* 39% Tap water (filtered)
* 20% Table salt
* 1.6% Cream of tartar
* 0.8% Vegetable oil
a|* Play-Doh

|C.3
|Gelatin with glycerin
a|Gelatin / Glycerin mix

* Gelatin: unflavored, unsweetened gelatin powder
* Gelatin shall have a Bloom hardness of approximately 220 – 265
* Glycerin shall be food grade
* Tap water filtered through a consumer-grade water filter
a|

|C.4
|Silicone
a|Commercial grade silicone

* Shall be two part platinum catalyzed
* Shall have a Shore A hardness of 10 to 40
* Shall be clear to slight milky color when cured
a|

|C.5
|Conductive coating
a|Conductive coating

* Can be carbon or metal loaded paints or inks
* Coatings may contain conductive particles or nanoparticles  
a|

|===

==== Modeling Compound Instructions
If the modeling compound will be prepared (as opposed to purchased), the compound shall be prepared using this recipe using common household kitchen items.

*Tools:*

* T.5 Consumer water filter

*Ingredients:*

* 1 cup all-purpose flour
* 1 tablespoon powdered alum
* 1/2 cup table salt
* 1 cup water, room temperature, filtered
* 1 tablespoon vegetable oil, room temperature
* Food coloring, gel based (optional)

*Recipe:*

. Mix all the dry ingredients.
. Stir in the oil and water.
. Cook over medium heat, stirring constantly until it reaches the consistency of mashed potatoes.
. Remove from heat and let cool to room temperature before use.

==== Gelatin with Glycerin Instructions
Some gelatins remain tacky when cooled. Gelatins selected should present a surface that does not stick too much to the sensor surface. Gelatins should leave very little if any residue when removed from the sensor surface.

When creating the gelatin with glycerin mixture, this recipe shall be used.

*Tools:*

* T.5 Consumer water filter

*Ingredients:*

* Unflavored, unsweetened gelatin powder with a Bloom hardness of approximately 220 – 265
* Food grade glycerin
* Tap water filtered through a consumer-grade water filter

*Recipe:*

. Mix equal parts by volume of gelatin, glycerin and tap water.
. Carefully heat in microwave or on heating plate until mixture is easily pourable.
.. Do not allow gelatin to boil. This will degrade the gelatin.
.. Stir as necessary throughout the heating process to fully mix and distribute the heat.
.. Be careful to minimize bubbles in the mixture. Some gelatins are more prone to developing bubbles than others.

The mixture should be poured into the mold(s) as soon as possible.

==== Silicone Instructions
. Obtain two part silicone with the following properties.
.. Shore A hardness of 10 to 40.
.. Platinum catalyzed silicones are preferred due to low shrinkage.
.. Clear to slight milky color when cured.
.. Sufficient working time to complete mixing, de-gassing as needed, adding fillers as needed, and transferring to mold.
.. Care should be taken to prevent contamination with cure inhibitors such as sulfur containing materials.
. Follow manufacturer instructions for mixing parts A and B to achieve advertised properties in the cured silicone.
.. Stir as necessary to fully mix.
... Mixing time can be lengthened by cooling the silicone.
... Curing time can be hastened by heating the mixed silicone in the cast. Follow manufacturer’s recommendation for accelerating curing times.
.. Be careful to minimize bubbles in the mixture.
... De-gas as needed.

=== Mold Materials

.Mold Material Requirements
[cols=".^1,.^1,.^3,.^2",options="header"]
|===

|ID
|Category
|Requirement
|Commercial Examples

|M.1
|Transparency material
a|Transparency material

* Shall be suitable for use in a laser printer
a|

|M.2
|Printed circuit board              
a|Printed circuit board

* Hobbyist grade is sufficient
* Epoxy laminates should have copper cladding thicknesses that correspond to one of the following:
** 35 μm = 1.38 mils = "1 oz" of copper
** 70 μm = 2.75 mils = "2 oz" of copper
* Substrate shall be at least 1.6 mm thick
a|

|M.3
|Dental Impression material
a|Dental Impression material

* Can be either polyvinyl siloxane (PVS) or polyether (PE) based or a hybrid PVS / PE material
a|

|===