= Fingerprint Toolbox Inventory
:showtitle:
:revdate: 2020-10-21

This document contains the inventory of tools and materials that are used in the context of the toolbox.

== Overview
This document specifies requirements for tools and materials that are used to create fingerprint friction ridge artefacts.  The requirements for each tool are specified in the following tables.

The evaluator may use any tools and materials to create fingerprint artefacts as long as they meet requirements specified below. The evaluator may use any available services (e.g. rental service) to prepare any tools in a cost effective way so long as the privacy of the biometric donor is protected.

The evaluator may need to use other tools that are not specified here.

Some examples:

* A mold release / wetting agent may be applied to the finger of the test subject.  This release / agent shall be compatible with the mold material as specified by the manufacturer of the mold material.
* The evaluator may procure a vacuum chamber to aid in the degassing of cast materials if desired.
* The evaluator may apply conductive coatings to a silicone cast to make the PAI conductive.  The coatings may be carbon or metal loaded paints or inks.  The coatings may contain conductive particles or nanoparticles.  Application of the coatings may be by brush or spray.  In all cases, the evaluator shall ensure that the dried conductive coating does not fill the friction ridge valleys thereby obscuring the fingerprint pattern.

== Tools Inventory
.Tool Requirements
[cols=".^1,.^1,3",options="header"]
|===
|ID
|Category
|Requirement


|T.1
|Cinferprint scanner
a|Commercial fingerprint scanner

* Scanner shall provide grayscale images in standard image file formats
* 1000 dpi minimum image resolution
* Rolled images preferred
* Touch/slap images acceptable

|T.2
|Image processing software
a|Photograph processing software

* Can be commercial, open source or bespoke
* Can be image manipulation software that allows pixel level image processing
* Can be automatic binarization software

|T.3
|Laser printer             
a|Small Office/Home Office Laser printer

* New printer shall be purchasable at the date of testing.

|T.4
|Printed Circuit Board (PCB) manufacturing kit            
a|PCB kit

* Hobbyist level commercial kit with fresh chemicals at the date of testing

|T.5
|Water filter           
a|Consumer grade tap water filter

* Can be faucet or pitcher based filter
* Must meet NSF/ANSI 42 and 53 contaminant reduction standards

|T.6
|Microwave oven            
a|Microwave oven

* Oven may be consumer grade
* Oven shall have a rotating turntable

|===


== Materials Inventory
All materials with expiration dates shall have an expiration date of three months beyond the date of testing.

.Cast Material Requirements
[cols=".^1,.^1,3",options="header"]
|===

|ID
|Category
|Requirement

|C.1
|Non-Newtonian fluid, also known as Dilatant compound
a|Commercial or custom made compound with a chemical composition approximating:

* 65% dimethylsiloxane (hydroxy-terminated polymers with boric acid)
* 17% silica (crystalline quartz)
* 9% Hydrogenated castor oil based thixotropic agent
* 4% polydimethylsiloxane
* 1% decamethyl cyclopentasiloxane
* 1% glycerin
* 1% titanium dioxide  

|C.2
|Modeling compound              
a|Commercial or custom made compound with a composition approximating:

* 39% General purpose baking flour
* 39% Tap water (filtered)
* 20% Table salt
* 1.6% Cream of tartar
* 0.8% Vegetable oil

|C.3
|Gelatin with glycerin
a|Gelatin / Glycerin mix

* Gelatin: unflavored, unsweetened gelatin powder
* Gelatin shall have a Bloom hardness of approximately 220 – 265
* Glycerin shall be food grade

|C.4
|Silicone
a|Commercial grade silicone

* Shall be two part platinum catalyzed
* Shall have a Shore A hardness of 10 to 40
* Shall be clear to slight milky color when cured

|C.5
|Conductive coating
a|Conductive coating

* Can be carbon or metal loaded paints or inks
* Coatings may contain conductive particles or nanoparticles  

|===

.Mold Material Requirements
[cols=".^1,.^1,3",options="header"]
|===

|ID
|Category
|Type 1

|M.1
|Transparency material
a|Transparency material

* Shall be suitable for use in a laser printer

|M.2
|Printed circuit board              
a|Printed circuit board

* Hobbyist grade is sufficient
* Copper cladding shall be of “2 oz.” thickness or approximately 2.74 mils thick
* Substrate shall be at least 1.6 mm thick

|M.3
|Eye Mimicry
|Dental Impression material

* Can be either polyvinyl siloxane (PVS) or polyether (PE) based or a hybrid PVS / PE material

|===