= Attack 2D Fingerprint 01-01

== Attack type
Non-Newtonian fluid cast made from transparency material mold.

=== Total Number of Species
This attack has *1* species to be tested.

== Overview
The evaluator captures a target user’s fingerprint with a commercial fingerprint scanner. Using the image from the scanner the evaluator produces a laser printer transparency mold. A non-Newtonian fluid PAI is made from the laser printer transparency mold and is presented to the TOE.

== Input
The fingers of a cooperative subjects for use in capturing images of the subjects’ friction ridge patterns. Images acquired under controlled and favorable conditions so as to acquire high quality friction ridge information.

== Attack Tools and Materials
* T.1 Fingerprint scanner
* T.2 Image processing software
* T.3 Laser printer
* C.1 Non-Newtonian fluid
* M.1 Transparency material

== Recipe - mold
. Obtain a binarized image of the target fingerprint. Make sure the ridge information is life size.
. Center the ridges in the image canvas of the photo manipulation software. The entire canvas should be at least twice the width and height of the area covered by the ridges. In other words, leave adequate space around the fingerprint so that casts made from the mold can be handled without touching the ridges. If multiple images are placed on one transparency, make sure to leave adequate working space between the images.
. Flip the image along the vertical axis producing a mirror image of the fingerprint.
. Invert the image so that the ridge lines are white and the remaining areas are black.
. Print the image(s) onto the transparency sheets.
.. Use the highest quality print mode possible. A minimum of 1000 dpi resolution should be used.
.. Avoid using duplex mode. The transparency should only make a single pass through the printer.

== Recipe - cast
. Obtain sufficient quantities of non-Newtonian fluid.
. Apply a small amount sufficient to cover the friction ridge pattern of the mold.
. Carefully remove the non-Newtonian fluid PAI from the mold.

Each PAI may be used only one time.

Store non-Newtonian fluid in an airtight container.

== Variations
N/A

== Prerequisite
The evaluator shall enroll test users first as described in the Fingerprint Toolbox Overview. If the ST covers multiple configurations for fingerprint unlock, the same test shall be performed for all configurations.

== Presentation
The evaluator shall present the PAI to the TOE as described in the Fingerprint Toolbox Overview.

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion
The evaluator should consider changing the following factors for penetration testing.

* Configuration of tools and materials
+
The evaluator may, for example, vary the temperature of the PAIs to change the stiffness of the friction ridges. Different non-Newtonian fluid manufactures may be used.

* Presentation method
+
The evaluator may vary the pressure, angle of rotation, region of the friction ridge pattern used to present the PAI to the TOE. The different fingers upon which the PAI is placed may be use when presenting the PAI.

*Attack Potential Rating Suggestion*

The attack potentials that are required to build the artefacts are summarized in the following tables. See BIOSD Section 9 for more information about how to calculate attack potential.

Some assumptions, based on current technology, are applied to the calculation of Attack Potential for this version of the toolbox. As PAD technology and PAIs become more sophisticated, these assumptions may change. Static determinations of values for the various factors as described below may then be replaced by values based on the specific PAI when calculating the Attack Potential.

Additionally, Attack Potential accounts for the time, expertise, etc. needed to make both the molds and the casts. When selecting the mold / cast combination consideration must be given to the overall ability to produce the mold separately from that needed for the cast. An attack based on an easy to make, inexpensive mold coupled with a very sophisticated cast process would necessarily be considered at the Attack Potential of the cast.  Because of this, in <<calculatedtable>>, the resulting attack potential is based on the highest score for each factor from the mold or cast. The individual attack potential for the mold or cast individually is shown in the tables after. The component column shows where the score comes from.

.Calculated Attack Potential 2D Fingerprint attack 01-01
[[calculatedtable]]
[cols=".^2,.^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
|===
|Factor 
|Component
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|_Mold, Cast are same_
|<= one week 
|1 
|<=one day 
|0 
|1

|*Expertise*
|_Mold, Cast are same_
|Layman
|0
|Layman
|0
|0

|*Knowledge of TOE*
|_Mold, Cast are same_
|Public
|0
|N/A
|
|0

a|*Window of Opportunity*

*(Access to TOE)*
|_Mold_
|Easy
|0
|Moderate
|4
|4

a|*Window of Opportunity*

*(Access to Biometric Characteristics)*
|_Cast_
|N/A
|
|Non-cooperative
|2
|2

|*Equipment*
|_Mold, Cast are same_
|Standard
|0
|Standard
|0
|0

7.+^.^|Calculated Total Attack Potential = 7 < Basic Attack Potential

|===

.Mold Attack Potential 2D Fingerprint attack 01-01
[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|<= one week 
|1 
|<=one day 
|0 
|1

|*Expertise*
|Layman
|0
|Layman
|0
|0

|*Knowledge of TOE*
|Public
|0
|N/A
|
|0

a|*Window of Opportunity*

*(Access to TOE)*
|Easy
|0
|N/A
|
|0

a|*Window of Opportunity*

*(Access to Biometric Characteristics)*
|N/A
|
|Non-cooperative
|2
|2

|*Equipment*
|Standard
|0
|Standard
|0
|0

6.+^.^|Mold-only Total Attack Potential = 3 < Basic Attack Potential

|===

.Cast Attack Potential 2D Fingerprint attack 01-01
[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|<= one week 
|1 
|<=one day 
|0 
|1

|*Expertise*
|Layman
|0
|Layman
|0
|0

|*Knowledge of TOE*
|Public
|0
|N/A
|
|0

a|*Window of Opportunity*

*(Access to TOE)*
|Easy
|0
|Moderate
|4
|4

a|*Window of Opportunity*

*(Access to Biometric Characteristics)*
|N/A
|
|N/A
|
|

|*Equipment*
|Standard
|0
|Standard
|0
|0

6.+^.^|Cast-only Total Attack Potential = 5 < Basic Attack Potential

|===

== Pass Criteria
There is no additional criteria other than what is defined in BIOSD and PAD Toolbox Overview.
