= Attack 2D Fingerprint 01-04

== Attack type

Silicone cast made from transparency material mold.

== Total Number of Species

This attack has *1* species to be tested.

== Overview

The evaluator captures a target user’s fingerprint with a commercial fingerprint scanner. Using the image from the scanner the evaluator produces a laser printer transparency mold. A silicone PAI is made from the laser printer transparency mold and is presented to the TOE.

== Input

The fingers of a cooperative subjects for use in capturing images of the subjects’ friction ridge patterns. Images acquired under controlled and favorable conditions so as to acquire high quality friction ridge information.

== Attack Tools and Materials

* T.1 Fingerprint scanner
* T.2 Image processing software
* T.3 Laser printer
* C.4 Silicone
* M.1 Transparency material

== Recipe - mold

[arabic]
. Obtain a binarized image of the target fingerprint. Make sure the ridge information is life size.
. Center the ridges in the image canvas of the photo manipulation software. The entire canvas should be at least twice the width and height of the area covered by the ridges. In other words, leave adequate space around the fingerprint so that casts made from the mold can be handled without touching the ridges. If multiple images are placed on one transparency, make sure to leave adequate working space between the images.
. Flip the image along the vertical axis producing a mirror image of the fingerprint.
. Invert the image so that the ridge lines are white and the remaining areas are black.
. Print the image(s) onto the transparency sheets.
[loweralpha]
.. Use the highest quality print mode possible. A minimum of 1000 dpi resolution should be used.
.. Avoid using duplex mode. The transparency should only make a single pass through the printer.

== Recipe - cast

[arabic]
. Obtain two part silicone with the following properties.
[loweralpha]
.. Shore A hardness of 10 to 40.
.. Platinum catalyzed silicones are preferred due to low shrinkage.
.. Clear to slight milky color when cured.
.. Sufficient working time to complete mixing, de-gassing as needed, adding fillers as needed, and transferring to mold.
.. Care should be taken to prevent contamination with cure inhibitors such as sulfur containing materials.
. Follow manufacturer instructions for mixing parts A and B to achieve advertised properties in the cured silicone.
[loweralpha]
.. Stir as necessary to fully mix.
[lowerroman]
... Mixing time can be lengthened by cooling the silicone.
... Curing time can be hastened by heating the mixed silicone in the cast. Follow manufacturer’s recommendation for accelerating curing times.
.. Be careful to minimize bubbles in the mixture.
[lowerroman]
... De-gas as needed.
. Pour mixture into clean dust free mold.
[loweralpha]
.. A release agent compatible with the mold and cast materials may be used if desired.
[lowerroman]
... Follow manufactures’ recommendations for using mold releases.
... If needed, remove mold release residue from cast before presentation to TOE.
.. Resulting cast should be thin enough to curve around tester’s finger when presented to TOE.
.. Place enough material in the mold to allow extra material to extend beyond the friction ridge area of the mold. This will facilitate handling the cast when removing from the mold and presenting it to the TOE.
. Allow silicone to thoroughly cure before removing from mold.
[loweralpha]
.. Be careful not to stretch the cast too much causing it to permanently deform or tear when removing from mold.
. Keep the friction ridge surface clean and dust free until presented to TOE.
. PAI may be reused until friction ridges show signs degradation.

== Variations
N/A

== Prerequisite
The evaluator shall enroll test users first as described in the Fingerprint Toolbox Overview. If the ST covers multiple configurations for fingerprint unlock, the same test shall be performed for all configurations.

== Presentation
The evaluator shall present the PAI to the TOE as described in the Fingerprint Toolbox Overview.

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion
The evaluator should consider changing the following factors for penetration testing.

* Configuration of tools and materials
+
The evaluator may, for example, vary the temperature of the PAIs to change the stiffness of the friction ridges. Different silicone manufactures may be used. The Shore hardness ratings can be varied within the approximate range listed. PAI optical clarity may be varied by using different silicones.

* Presentation method
+
The evaluator may vary the pressure, angle of rotation, region of the friction ridge pattern used to present the PAI to the TOE. The different fingers upon which the PAI is placed may be use when presenting the PAI.

== Attack Potential Rating Suggestion
The attack potentials that are required to build the artefacts are summarized in the following table. See BIOSD Section 9 for more information about how to calculate attack potential.

Some assumptions, based on current technology, are applied to the calculation of Attack Potential for this version of the toolbox. As PAD technology and PAIs become more sophisticated, these assumptions may change. Static determinations of values for the various factors as described below may then be replaced by values based on the specific PAI when calculating the Attack Potential.

Attack Potential accounts for the time, expertise, etc. needed to make both the molds and the casts. When selecting the mold / cast combination consideration must be given to the overall ability to produce the mold separately from that needed for the cast. An attack based on an easy to make, inexpensive mold coupled with a very sophisticated cast process would necessarily be considered at the Attack Potential of the cast. Therefore, the Attack Potential of a given mold / cast combination takes on the higher Attack Potential of the pair. This is reflected in the table below.

.Attack Potential 2D Fingerprint attack 01-04
[cols=".^2,.^2,^.^1,.^2,^.^1,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|
4.+^.^|*Mold* 
4.+^.^|*Cast* 
|

|*Elapsed Time*
|<= one week 
|1 
|<=one day 
|0 
|<= one week 
|1 
|<=one day 
|0 
|1

|*Expertise*
|Layman
|0
|Layman
|0
|Layman
|0
|Layman
|0
|0

|*Knowledge of TOE*
|Public
|0
|N/A
|
|Public
|0
|N/A
|
|0

a|*Window of Opportunity*

*(Access to TOE)*
|Easy
|0
|Moderate
|4
|Easy
|0
|Moderate
|4
|4

a|*Window of Opportunity*

*(Access to Biometric Characteristics)*
|N/A
|
|Without notice
|0
|N/A
|
|Without notice
|0
|0

|*Equipment*
|Standard
|0
|Standard
|0
|Standard
|0
|Standard
|0
|0

10.+^.^|Total Attack Potential = 5 < Basic Attack Potential

|===

== Pass Criteria
There is no additional criteria other than what is defined in BIOSD and PAD Toolbox Overview.