= Attack 2D Fingerprint 02-02

== Attack type
Modeling compound cast made from printed circuit board (PCB) mold.

== Total Number of Species
This attack has *1* species to be tested.

== Overview
The evaluator captures a target user’s fingerprint with a commercial fingerprint scanner. Using the image from the scanner the evaluator produces a PCB mold. A modeling compound PAI is made from the PCB mold and is presented to the TOE.

== Input
The fingers of a cooperative subjects for use in capturing images of the subjects’ friction ridge patterns. Images acquired under controlled and favorable conditions so as to acquire high quality friction ridge information.

== Attack Tools and Materials
* T.1 Fingerprint scanner
* T.2 Image processing software
* T.3 Laser printer
* T.5 Water filter
* C.2 Modeling compound
* M.2 Printed circuit board (PCB)

== Recipe - mold
[arabic]
. Obtain a binarized image of the target fingerprint. Make sure the ridge information is life size.
. Center the ridges in the image canvas. The entire canvas should be at least twice the width and height of the area covered by the ridges. In other words, leave adequate space around the fingerprint so that casts made from the mold can be handled without touching the ridges. If multiple images are placed on one PCB blank, make sure to leave adequate working space between the images.
. Flip the image along the vertical axis producing a mirror image of the fingerprint.
. Invert the image so that the ridge lines are white and the remaining areas are black.
. Follow PCB manufacturer instructions for producing a printed circuit board. These instructions will vary depending on manufacturer and method of transferring the image to the PCB blank. The process used should be documented in the test report.
. Be careful to not leave the PCB in the etching solution longer than needed to achieve clean substrate in the ridge areas. Doing so will cause the copper under the etch-resist material to be etched away.

== Recipe - cast
The molding compound described here is an approximation of a common modeling compound sold as a child’s toy. This recipe or the commercial equivalent may be used. The test report shall specify which version is used.

[arabic]
. Obtain or prepare sufficient quantities of modeling compound. If preparing the compound follow the below steps, otherwise skip to step 2.
[loweralpha]
.. This recipe uses ingredients commonly found in household kitchens. Collect the following ingredients.
[lowerroman]
... 1 cup all-purpose flour
... 1 tablespoon powdered alum
... 1/2 cup table salt
... 1 cup water, room temperature
... 1 tablespoon vegetable oil, room temperature
... Food coloring, gel based (optional)
.. Mix all the dry ingredients.
.. Stir in the oil and water.
.. Cook over medium heat, stirring constantly until it reaches the consistency of mashed potatoes.
.. Remove from heat and let cool to room temperature before use.
. Apply a small amount of modeling compound sufficient to cover the friction ridge pattern of the mold.
. Carefully remove the modeling compound PAI from the mold.

Each PAI may be used only one time.

Store modeling compound in an airtight container.

== Variations
N/A

== Prerequisite
The evaluator shall enroll test users first as described in the Fingerprint Toolbox Overview. If the ST covers multiple configurations for fingerprint unlock, the same test shall be performed for all configurations.

== Presentation
The evaluator shall present the PAI to the TOE as described in the Fingerprint Toolbox Overview.

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion
The evaluator should consider changing the following factors for penetration testing.

* Configuration of tools and materials
+
The evaluator may, for example, vary the temperature of the PAIs to change the stiffness of the friction ridges. Different modeling compound manufactures may be used. The PAIs may be allowed to dry for a short time before being presented to the TOE. If commercial compound is used, different colors may be procured. The literature shows different presentation attack performance can be achieved with different colors.

Copper cladding thickness can be varied to produce differing height ridges in the casts.

* Presentation method
+
The evaluator may vary the pressure, angle of rotation, region of the friction ridge pattern used to present the PAI to the TOE. The different fingers upon which the PAI is placed may be use when presenting the PAI.

== Attack Potential Rating Suggestion
The attack potentials that are required to build the artefacts are summarized in the following table. See BIOSD Section 9 for more information about how to calculate attack potential.

Some assumptions, based on current technology, are applied to the calculation of Attack Potential for this version of the toolbox. As PAD technology and PAIs become more sophisticated, these assumptions may change. Static determinations of values for the various factors as described below may then be replaced by values based on the specific PAI when calculating the Attack Potential.

Attack Potential accounts for the time, expertise, etc. needed to make both the molds and the casts. When selecting the mold / cast combination consideration must be given to the overall ability to produce the mold separately from that needed for the cast. For example, an attack based on an easy to make, inexpensive mold coupled with a very sophisticated cast process would necessarily be considered at the Attack Potential of the cast. Therefore, the Attack Potential of a given mold / cast combination takes on the higher Attack Potential of the pair. This is reflected in the table below.

.Attack Potential 2D Fingerprint attack 02-02
[cols=".^2,.^2,^.^1,.^2,^.^1,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|
4.+^.^|*Mold* 
4.+^.^|*Cast* 
|

|*Elapsed Time*
|<= one week 
|1 
|<=one day 
|0 
|<= one week 
|1 
|<=one day 
|0 
|1

|*Expertise*
|Layman
|0
|Layman
|0
|Layman
|0
|Layman
|0
|0

|*Knowledge of TOE*
|Public
|0
|N/A
|
|Public
|0
|N/A
|
|0

a|*Window of Opportunity*

*(Access to TOE)*
|Easy
|0
|Moderate
|4
|Easy
|0
|Moderate
|4
|4

a|*Window of Opportunity*

*(Access to Biometric Characteristics)*
|N/A
|
|Without notice
|0
|N/A
|
|Without notice
|0
|0

|*Equipment*
|Standard
|0
|Standard
|0
|Standard
|0
|Standard
|0
|0

10.+^.^|Total Attack Potential = 5 < Basic Attack Potential

|===

== Pass Criteria
There is no additional criteria other than what is defined in BIOSD and PAD Toolbox Overview.