= Attack 3D Fingerprint 03-03

== Attack type
A gelatin / glycerin mix cast made from dental impression material mold.

=== Total Number of Species
This attack has *1* species to be tested.

== Overview
The evaluator captures a target user’s fingerprint with a commercial fingerprint scanner. Using the image from the scanner the evaluator produces a dental impression mold. A gelatin with glycerin PAI is made from the dental impression mold and is presented to the TOE.

== Input
The fingers of a cooperative subjects for use in capturing images of the subjects’ friction ridge patterns. Images acquired under controlled and favorable conditions so as to acquire high quality friction ridge information.

== Attack Tools and Materials
* T.5 Water filter
* T.6 Microwave oven
* C.3 Gelatin with glycerin
* M.3 Dental impression material

== Recipe - mold
. Prepare a suitable container for the liquid mold material.
.. The container should be large enough to contain adequate material sufficient to cover the entire ridge area of the target finger from the tip to the first joint crease.
.. The container should be shaped such that the target finger can be laid down at a shallow angle to the surface of the impression material.
. Make sure the target finger is clean and dry.
. If needed apply mold release to the target finger following the manufacturer instructions.
. Prepare the mold material according to manufacturer instructions.
. Fill the container with sufficient impression material to cover the entire ridge area of the target finger from the tip to the first joint crease.
. Immediately place the target finger into the impression material holding it stationary until the material is completely set up following manufacturer instructions.
. Be careful that the target finger does not touch the bottom of the container. The finger should “float” in the impression material.
. Carefully remove the finger from the material. Rolling or “peeling” the finger from the mold may help with the release.
. Allow the mold to sit for 15 minutes before use to ensure curing is complete.
. Keep the mold clean and dust free until use.

== Recipe - cast
. Prepare a suitable quantity of gelatin mixture to create the PAI.
. Pour gelatin mixture into mold as soon as possible.
.. Resulting cast should be thin enough to curve around tester’s finger when presented to TOE.
.. Place enough material in the mold to allow extra material to extend beyond the friction ridge area of the mold. This will facilitate handling the cast when removing from the mold and presenting it to the TOE.
. Cool mixture thoroughly before removing from mold.
.. Be careful not to stretch the cast too much causing it to permanently deform or tear when removing from mold.
. Present to TOE as soon after removal from mold as practical.
. PAI may be reused until it dries out too much to be effective or the friction ridges show signs degradation. If properly produced and stored, PAI’s should have a shelf life of several months.

Store PAIs in an airtight container.

== Variations
N/A

== Prerequisite
The evaluator shall enroll test users first as described in the Fingerprint Toolbox Overview. If the ST covers multiple configurations for fingerprint unlock, the same test shall be performed for all configurations.

== Presentation
The evaluator shall present the PAI to the TOE as described in the Fingerprint Toolbox Overview.

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion

The evaluator should consider changing the following factors for penetration testing.

* Configuration of tools and materials
+
The evaluator may, for example, vary the temperature of the PAIs to change the stiffness of the friction ridges. Gelatins from different manufactures may be used. Different bloom hardness gelatins may be used. The gelatin / glycerin / water ratio may be varied.
+
Different dental impression materials can be used.

* Presentation method
+
The evaluator may vary the pressure, angle of rotation, region of the friction ridge pattern used to present the PAI to the TOE. The evaluator may place the PAI on a different finger for presentation.

=== Attack Potential Rating Suggestion
The attack potentials that are required to build the artefacts are summarized in the following tables. See BIOSD Section 9 for more information about how to calculate attack potential.

Some assumptions, based on current technology, are applied to the calculation of Attack Potential for this version of the toolbox. As PAD technology and PAIs become more sophisticated, these assumptions may change. Static determinations of values for the various factors as described below may then be replaced by values based on the specific PAI when calculating the Attack Potential.

There are three attack potential tables below. Attack Potential tables for Identification account for the time, expertise, etc. required to make the mold (<<moldtable>>) and the cast (<<casttable>>) described in this attack. When selecting the mold / cast combination consideration must be given to the ability to produce the mold separately from that needed for the cast. Because of this, the resulting attack potential for Identification in <<calculatedtable>> is the sum of the mold (<<moldtable>>) and cast (<<casttable>>) score. 

The sum of the Identification is calculated based on the factor. Elapsed Time is calculated as a simple mathematical sum, the addition of the individual time values for the cast and mold. For example, an Elapsed Time for the mold of <= one week and for the cast of <= one day when added results in a total of <= 8 days which is assigned the Identification Value of <= two weeks. For the other factors, the sum equals the value of the highest score. For example, an Equipment factor of Standard equipment for the mold combined with an Equipment factor of Specialized equipment for the cast would result in the Identification Value of Specialized equipment for that factor.

Attack potential for Exploitation that corresponds to the effort to attack the TOE using the PAI in the actual environment (i.e. capturing the fingerprint image from the target and attack the TOE using the cast created with the image and mold) is defined in <<calculatedtable>>. This <<calculatedtable>> shows the final attack potential to rate the vulnerabilities and TOE resistance.

.Calculated Attack Potential 3D Fingerprint attack 03-03
[[calculatedtable]]
[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|<= two weeks 
|2 
|<=one day 
|0 
|2

|*Expertise*
|Layman
|0
|Layman
|0
|0

|*Knowledge of TOE*
|Public
|0
|N/A
|
|0

a|*Window of Opportunity*

*(Access to TOE)*
|Easy
|0
|Moderate
|4
|4

a|*Window of Opportunity*

*(Access to Biometric Characteristics)*
|N/A
|
|Non-cooperative
|2
|2

|*Equipment*
|Standard
|0
|Standard
|0
|0

6.+^.^|Calculated Total Attack Potential = 8 < Basic Attack Potential

|===

.Mold Attack Potential 3D Fingerprint attack 03-03
[[moldtable]]
[cols=".^2,.^2,^.^1",options="header",]
|===
|Factor 
|Identification Value
|Score

|*Elapsed Time*
|<= one week 
|1 

|*Expertise*
|Layman
|0

|*Knowledge of TOE*
|Public
|0

a|*Window of Opportunity*

*(Access to TOE)*
|Easy
|0

a|*Window of Opportunity*

*(Access to Biometric Characteristics)*
|N/A
|

|*Equipment*
|Standard
|0
6.+^.^|Mold-only Total Attack Potential for Identification = 1

|===

.Cast Attack Potential 3D Fingerprint attack 03-03
[[casttable]]
[cols=".^2,.^2,^.^1",options="header",]
|===
|Factor 
|Identification Value
|Score

|*Elapsed Time*
|<= one week 
|1 

|*Expertise*
|Layman
|0

|*Knowledge of TOE*
|Public
|0

a|*Window of Opportunity*

*(Access to TOE)*
|Easy
|0

a|*Window of Opportunity*

*(Access to Biometric Characteristics)*
|N/A
|

|*Equipment*
|Standard
|0

6.+^.^|Cast-only Total Attack Potential = 1

|===

== Pass Criteria
There is no additional criteria other than what is defined in BIOSD and PAD Toolbox Overview.